default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  #####追加#####
  host: db
  username: postgres
  passowrd: passowrd
  #############

development:
  <<: *default
  database: digihai_development

test:
  <<: *default
  database: digihai_test

production:
  <<: *default
  database: digihai_production
  username: digihai
  password: <%= ENV['DIGIHAI_DATABASE_PASSWORD'] %>
